---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-build
spec:
  workspaces:
    - name: source
      description: The git repo
  steps:
    - name: run-install
      image: quay.io/redhat-cop/uncontained-local-dev
      workingDir: /workspace/source
      command: ["npm"]
      args:
        - "install"
    - name: run-build
      image: quay.io/redhat-cop/uncontained-local-dev
      workingDir: /workspace/source
      command: ["npm"]
      args:
        - "run"
        - "build"
